// <auto-generated />
using System;
using System.Text.Json;
using BEScanCV.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BEScanCV.Infrastructure.Migrations
{
    [DbContext(typeof(BEScanCvDbContext))]
    partial class BEScanCvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvCertification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CvInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cv_info_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CvInfoId");

                    b.ToTable("cv_certification", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AiDocumentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ai_document_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("AiDocumentId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("cv_files", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CvFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("cv_file_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<JsonDocument>("Educations")
                        .HasColumnType("jsonb")
                        .HasColumnName("educations");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsMarked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_marked");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.Property<JsonDocument>("ProfileData")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_data");

                    b.Property<JsonDocument>("QualityDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_details");

                    b.Property<string>("QualityReason")
                        .HasColumnType("text")
                        .HasColumnName("quality_reason");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("New")
                        .HasColumnName("tag");

                    b.Property<int?>("TotalExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("total_experience_years");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.HasIndex("CvFileId")
                        .IsUnique();

                    b.ToTable("cv_infos", null, t =>
                        {
                            t.HasCheckConstraint("cv_infos_tag_check", "tag IN ('New', 'Contracted', 'In-Process', 'Rejected', 'Hired')");

                            t.HasCheckConstraint("cv_infos_work_type_check", "work_type IS NULL OR work_type IN ('Remote', 'Full-time', 'Part-time')");
                        });
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CvInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cv_infos_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CvInfoId");

                    b.HasIndex("Name");

                    b.ToTable("cv_skills", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvUploadBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("CancelledFiles")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_files");

                    b.Property<int>("CompletedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("completed_files");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("failed_files");

                    b.Property<int>("PendingFiles")
                        .HasColumnType("integer")
                        .HasColumnName("pending_files");

                    b.Property<int>("ProcessingFiles")
                        .HasColumnType("integer")
                        .HasColumnName("processing_files");

                    b.Property<string>("RequestIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedBy");

                    b.ToTable("cv_upload_batches", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvUploadBatchItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CvUploadBatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cv_upload_batch_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("QUEUE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CvUploadBatchId");

                    b.HasIndex("Status");

                    b.ToTable("batch_upload_items", null, t =>
                        {
                            t.HasCheckConstraint("batch_upload_items_status_check", "status IN ('QUEUE', 'PROCESSING', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvWorkExperience", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company");

                    b.Property<long>("CvInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cv_info_id");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("duration");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.Property<string>("Responsibility")
                        .HasColumnType("text")
                        .HasColumnName("responsibility");

                    b.HasKey("Id");

                    b.HasIndex("CvInfoId");

                    b.ToTable("work_experience", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvCertification", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.CvInfo", "CvInfo")
                        .WithMany("CvCertifications")
                        .HasForeignKey("CvInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvInfo");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvFile", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.User", "Uploader")
                        .WithMany("CvFiles")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvInfo", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.CvFile", "CvFile")
                        .WithOne("CvInfo")
                        .HasForeignKey("BEScanCV.Domain.Entities.CvInfo", "CvFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvFile");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvSkill", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.CvInfo", "CvInfo")
                        .WithMany("CvSkills")
                        .HasForeignKey("CvInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvInfo");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvUploadBatch", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.User", "Uploader")
                        .WithMany("CvUploadBatches")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvUploadBatchItem", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.CvUploadBatch", "CvUploadBatch")
                        .WithMany("Items")
                        .HasForeignKey("CvUploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvUploadBatch");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvWorkExperience", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.CvInfo", "CvInfo")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("CvInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvInfo");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BEScanCV.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvFile", b =>
                {
                    b.Navigation("CvInfo");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvInfo", b =>
                {
                    b.Navigation("CvCertifications");

                    b.Navigation("CvSkills");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.CvUploadBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BEScanCV.Domain.Entities.User", b =>
                {
                    b.Navigation("CvFiles");

                    b.Navigation("CvUploadBatches");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
